/**
 * The clue dictionary for Mini Crossword (docs/games/mini-crossword.md). One clue per word,
 * written for this game, so there is nothing licensed and no puzzle count to run out of: the
 * filler lays a fresh grid from these words and every word in it already has its clue.
 *
 * A clue is short, plain and says one thing. Where a word has several meanings the clue picks the
 * one a person reaches for first. Three, four and five letters only, which is all a 5x5 holds.
 */
export const CLUES: Readonly<Record<string, string>> = {
  // Three letters
  ace: 'Top card, or a perfect serve',
  act: 'Part of a play',
  add: 'Put two numbers together',
  age: 'How many years old',
  aim: 'Point at a target',
  air: 'What you breathe',
  ale: 'Beer, the older word for it',
  all: 'Every last one',
  ant: 'Tiny worker in a colony',
  ape: 'Gorilla or chimp',
  arc: 'Curve of a rainbow',
  arm: 'Shoulder to hand',
  art: 'What hangs in a gallery',
  ash: 'What is left after a fire',
  ask: 'Put a question',
  bag: 'What the shopping goes in',
  bar: 'Where drinks are poured',
  bat: 'Cricket kit, or a night flyer',
  bay: 'Curve of coast',
  bed: 'Where you sleep',
  bee: 'Honey maker',
  bet: 'Money on a guess',
  bid: 'Offer at an auction',
  big: 'Far from small',
  bin: 'Where rubbish goes',
  bit: 'A small amount',
  bow: 'It shoots arrows, or you take one on stage',
  box: 'Cardboard container',
  boy: 'Young lad',
  bug: 'Beetle, or a fault in a program',
  bus: 'It stops at every stop',
  cab: 'Taxi',
  cap: 'Hat with a peak',
  car: 'Four wheels and a engine',
  cat: 'It purrs',
  cow: 'It gives milk',
  cry: 'Let the tears out',
  cup: 'You drink tea from it',
  cut: 'Take a knife to it',
  dam: 'Wall that holds a river',
  day: 'Sunrise to sunrise',
  den: 'Cosy little room',
  dig: 'Make a hole',
  dim: 'Not at all bright',
  dog: 'It fetches',
  dot: 'Full stop',
  dry: 'Without a drop of water',
  due: 'Expected any minute',
  ear: 'You hear with it',
  eat: 'Have a meal',
  egg: 'Breakfast, from a hen',
  elm: 'Tall shade tree',
  end: 'The last of it',
  era: 'A long stretch of history',
  eve: 'The night before',
  eye: 'You see with it',
  fan: 'It moves the air, or cheers the team',
  far: 'A long way off',
  fat: 'Not thin',
  few: 'Hardly any',
  fig: 'Soft purple fruit',
  fin: 'A fish steers with it',
  fit: 'In good shape',
  fix: 'Mend it',
  fly: 'Take to the air',
  fog: 'Cloud at ground level',
  fox: 'Red-coated raider',
  fun: 'A good time',
  fur: 'Warm animal coat',
  gap: 'Space between two things',
  gas: 'It fuels the cooker',
  gem: 'Cut stone worth keeping',
  get: 'Come by it',
  gum: 'You chew it',
  gun: 'It fires',
  gut: 'Belly, or instinct',
  ham: 'Sandwich meat',
  hat: 'You wear it on your head',
  hay: 'Dried grass for horses',
  hen: 'She lays the eggs',
  hip: 'Joint above the leg',
  hit: 'Strike it, or a song everybody knows',
  hot: 'Straight off the stove',
  hub: 'Middle of a wheel',
  hug: 'Arms all the way round',
  ice: 'Frozen water',
  ink: 'What a pen runs out of',
  inn: 'Old roadside pub',
  ion: 'Atom with a charge',
  jam: 'It goes on toast, or blocks the road',
  jar: 'Glass pot with a lid',
  jaw: 'It works when you chew',
  jet: 'Fast plane',
  job: 'What you go to work for',
  jog: 'Slow run',
  joy: 'Pure happiness',
  key: 'It opens the door',
  kid: 'Young goat, or a child',
  kit: 'Everything you need for the job',
  lab: 'Where the experiments happen',
  lap: 'One time round the track',
  law: 'What the courts go by',
  lay: 'Put it down flat',
  leg: 'You stand on two',
  let: 'Allow it',
  lid: 'Top of a jar',
  lie: 'Something untrue',
  lip: 'Edge of the mouth',
  log: 'Cut piece of tree',
  lot: 'A great many',
  low: 'Near the ground',
  mad: 'Out of your mind',
  man: 'Grown lad',
  map: 'It shows you the way',
  mat: 'You wipe your feet on it',
  mix: 'Stir it all together',
  mud: 'Wet earth',
  mug: 'Big cup with a handle',
  nap: 'Short sleep',
  net: 'It catches fish, or the ball',
  new: 'Straight out of the box',
  nod: 'Say yes without speaking',
  nut: 'It comes in a shell',
  oak: 'Tree that drops acorns',
  oar: 'You row with it',
  odd: 'Not even, or a bit strange',
  oil: 'It goes in the pan',
  old: 'Been around a long time',
  one: 'The first number',
  orb: 'Perfect sphere',
  owe: 'Have to pay it back',
  owl: 'It hunts by night',
  own: 'Have it to yourself',
  pad: 'Paper to write on',
  pan: 'You fry in it',
  paw: 'A dog has four',
  pay: 'Hand over the money',
  pea: 'Little green ball',
  pen: 'You write with it',
  pet: 'Animal at home',
  pie: 'Pastry with a filling',
  pin: 'It holds the cloth together',
  pit: 'Deep hole',
  pod: 'Where the peas live',
  pot: 'It sits on the stove',
  pub: 'Where the locals drink',
  pup: 'Young dog',
  put: 'Set it down',
  rag: 'Old cloth',
  ram: 'Male sheep',
  ran: 'Went at speed',
  rat: 'Long-tailed rodent',
  raw: 'Not cooked',
  ray: 'Line of light',
  red: 'The colour of a stop sign',
  rib: 'Bone round the chest',
  rid: 'Be done with it',
  rim: 'Edge of a wheel',
  rip: 'Tear it',
  rob: 'Take what is not yours',
  rod: 'Straight bar, or fishing kit',
  row: 'A line of seats',
  rub: 'Work at it with a cloth',
  rug: 'Small carpet',
  run: 'Go flat out',
  sad: 'Down in the mouth',
  sap: 'What runs inside a tree',
  saw: 'It cuts wood',
  sea: 'Salt water everywhere',
  see: 'Take it in with your eyes',
  set: 'Put it in place',
  shy: 'Happier at the back',
  sip: 'A small drink',
  sit: 'Take a chair',
  six: 'Half a dozen',
  ski: 'Slide down the snow',
  sky: 'It is blue on a good day',
  sly: 'Quietly clever',
  son: 'Boy of the family',
  sow: 'Put seed in the ground',
  spy: 'They work in secret',
  sun: 'It rises in the east',
  tag: 'Label, or a chasing game',
  tan: 'What the sun leaves',
  tap: 'Water comes out of it',
  tar: 'Black stuff on the road',
  tea: 'A cup of it fixes most things',
  ten: 'Fingers on two hands',
  tie: 'It goes round a collar',
  tin: 'Can of beans',
  tip: 'Point, or money for good service',
  toe: 'The foot has five',
  ton: 'A thousand kilos',
  top: 'The highest part',
  toy: 'Something to play with',
  try: 'Give it a go',
  tub: 'Round open container',
  tug: 'Pull it hard',
  urn: 'Big pot for tea or ashes',
  van: 'Small lorry',
  vet: 'Doctor for animals',
  vow: 'Promise you mean',
  wag: 'What a happy tail does',
  war: 'The opposite of peace',
  wax: 'A candle is made of it',
  way: 'The road to take',
  web: 'A spider spins it',
  wet: 'Soaked through',
  who: 'Which person',
  why: 'For what reason',
  wig: 'Hair you can take off',
  win: 'Come first',
  wit: 'Quick humour',
  yes: 'The opposite of no',
  zip: 'It does up a coat',
  zoo: 'Where the lions live',

  // Four letters
  able: 'Up to the job',
  acid: 'Sour, and it burns',
  acre: 'Field measure',
  atom: 'Smallest piece of an element',
  aunt: 'Your parent\'s sister',
  away: 'Not here',
  baby: 'Newest of the family',
  back: 'Behind you',
  bake: 'Put it in the oven',
  ball: 'It bounces',
  band: 'They play together',
  bank: 'Where the money sits',
  bare: 'Nothing on it',
  barn: 'Where the hay is kept',
  base: 'What it stands on',
  bath: 'A long soak',
  beam: 'Ray of light, or a roof timber',
  bean: 'It comes in a pod',
  bear: 'Big furry forest dweller',
  beat: 'Rhythm of a song',
  bell: 'It rings',
  belt: 'It holds your trousers up',
  bend: 'Curve in the road',
  best: 'Better than all the rest',
  bike: 'Two wheels and pedals',
  bird: 'It has feathers',
  bite: 'Take a chunk out',
  blue: 'Colour of the sky',
  boat: 'It floats',
  body: 'Head to toe',
  boil: 'Bring to a hundred degrees',
  bold: 'Not afraid at all',
  bone: 'There are two hundred odd',
  book: 'Pages between covers',
  boot: 'Tall shoe',
  born: 'Brought into the world',
  both: 'The pair of them',
  bowl: 'Soup goes in it',
  brew: 'Make the tea',
  bulb: 'It lights the room',
  bulk: 'Most of it',
  burn: 'What fire does',
  bush: 'Small shrub',
  busy: 'No time to spare',
  cage: 'Bars round a bird',
  cake: 'Candles go on it',
  calm: 'Not a ripple',
  camp: 'Tents for the night',
  cane: 'Walking stick',
  card: 'You send one at Christmas',
  care: 'Look after it',
  cart: 'You pull it',
  case: 'Suitcase, or a matter for court',
  cash: 'Notes and coins',
  cast: 'Everybody in the play',
  cave: 'Hole in a hillside',
  cell: 'Small room, or part of a body',
  chat: 'A friendly talk',
  chef: 'They run the kitchen',
  chin: 'Below the mouth',
  city: 'Big town',
  clay: 'Pots are made of it',
  clip: 'Hold it together',
  club: 'Where members meet',
  coal: 'Black rock that burns',
  coat: 'You put it on to go out',
  code: 'Secret writing',
  coin: 'Round money',
  cold: 'Wrap up warm',
  cook: 'Make the dinner',
  cool: 'Pleasantly cold',
  copy: 'Make another one',
  cord: 'Thin rope',
  corn: 'It grows on a cob',
  cost: 'What you pay',
  crab: 'It walks sideways',
  crew: 'Those who sail the ship',
  crop: 'What the farmer grows',
  crow: 'Big black bird',
  cube: 'Six square sides',
  cuff: 'End of a sleeve',
  cure: 'Make the illness go',
  curl: 'Twist of hair',
  dark: 'No light at all',
  dash: 'A quick run',
  date: 'Day on the calendar',
  dawn: 'First light',
  deal: 'An agreement',
  dear: 'Much loved, or costly',
  debt: 'What you owe',
  deck: 'Floor of a ship',
  deep: 'A long way down',
  deer: 'It has antlers',
  desk: 'You work at it',
  dice: 'You roll them',
  diet: 'What you eat',
  dine: 'Sit down to dinner',
  dirt: 'Earth, or what needs washing off',
  dish: 'Plate or bowl',
  dive: 'Head first into the water',
  dock: 'Where ships tie up',
  doll: 'Toy person',
  door: 'You knock on it',
  dose: 'How much medicine',
  dove: 'Bird of peace',
  down: 'Towards the floor',
  drag: 'Pull it along',
  draw: 'Make a picture, or tie the game',
  drip: 'One drop at a time',
  drop: 'Let it fall',
  drum: 'You hit it to keep time',
  duck: 'It quacks',
  dull: 'Nothing interesting about it',
  dusk: 'Last light of the day',
  dust: 'It settles on the shelf',
  duty: 'What you must do',
  each: 'Every single one',
  earn: 'Get it by working',
  east: 'Where the sun comes up',
  easy: 'No trouble at all',
  edge: 'Where it stops',
  exit: 'The way out',
  face: 'Eyes, nose and mouth',
  fact: 'Something true',
  fade: 'Lose the colour',
  fair: 'Even handed',
  fall: 'Come down hard',
  farm: 'Fields and a barn',
  fast: 'At speed',
  fate: 'What was going to happen anyway',
  fear: 'What keeps you awake',
  feed: 'Give it a meal',
  feel: 'Touch it',
  fern: 'Green plant with fronds',
  file: 'Papers in one place',
  fill: 'Right to the top',
  film: 'What you watch',
  find: 'Come across it',
  fine: 'Quite all right',
  fire: 'It needs putting out',
  firm: 'Solid to the touch',
  fish: 'It swims',
  fist: 'Closed hand',
  flag: 'It flies on a pole',
  flat: 'No bumps at all',
  flee: 'Run for it',
  flow: 'What a river does',
  folk: 'Ordinary people',
  food: 'What is on the plate',
  fool: 'Somebody being silly',
  foot: 'Twelve inches',
  fork: 'It goes with the knife',
  form: 'Shape, or a paper to fill in',
  fort: 'Walls built to hold out',
  four: 'One more than three',
  free: 'Costs nothing',
  frog: 'It hops and croaks',
  fuel: 'What the engine burns',
  full: 'No room left',
  fund: 'Money set aside',
  gain: 'Come out ahead',
  game: 'What we make here',
  gate: 'You open it to get in',
  gear: 'Kit, or a cog',
  gift: 'A present',
  girl: 'Young lass',
  give: 'Hand it over',
  glad: 'Pleased about it',
  glow: 'Soft light',
  goal: 'Where the ball goes',
  goat: 'It climbs anything',
  gold: 'Metal worth having',
  good: 'The opposite of bad',
  gown: 'Long dress',
  grab: 'Take it quickly',
  gray: 'Between black and white',
  grin: 'A wide smile',
  grip: 'Hold it tight',
  grow: 'Get bigger',
  gulf: 'Wide bay',
  hail: 'Ice from the sky',
  hair: 'It grows on your head',
  half: 'One of two equal parts',
  hall: 'The room you come into',
  halt: 'Stop right there',
  hand: 'Five fingers',
  hang: 'Put it on a hook',
  hard: 'Not easy at all',
  harm: 'Do it damage',
  hawk: 'Sharp-eyed hunter',
  heap: 'A pile of it',
  hear: 'Take it in with your ears',
  heat: 'What the oven gives',
  heel: 'Back of the foot',
  help: 'Lend a hand',
  herb: 'It goes in the pot for flavour',
  herd: 'Cows together',
  hero: 'They save the day',
  hide: 'Put it out of sight',
  high: 'Well off the ground',
  hill: 'Small mountain',
  hint: 'A small clue',
  hire: 'Take somebody on',
  hold: 'Keep it in your hands',
  hole: 'A gap right through',
  holy: 'Set apart as sacred',
  home: 'Where you live',
  hook: 'It catches the fish',
  hope: 'What keeps you going',
  horn: 'It grows on a bull',
  hose: 'Water runs through it',
  host: 'They have the guests',
  hour: 'Sixty minutes',
  huge: 'Very big indeed',
  hunt: 'Go looking for it',
  hurt: 'Cause pain',
  idea: 'A thought worth having',
  inch: 'Small measure',
  iron: 'Metal, or what flattens shirts',
  item: 'One thing on a list',
  jazz: 'Music with swing',
  join: 'Put them together',
  joke: 'Meant to make you laugh',
  jump: 'Both feet off the ground',
  junk: 'Stuff worth nothing',
  keen: 'Very interested',
  keep: 'Hang on to it',
  kind: 'Good to others',
  king: 'He wears the crown',
  kiss: 'A touch of the lips',
  knee: 'Joint in the leg',
  knit: 'Make a jumper with needles',
  knot: 'Tie in a rope',
  lace: 'It ties your shoe',
  lack: 'Not have enough',
  lake: 'Water with land all round',
  lamb: 'Young sheep',
  lamp: 'It stands on the table',
  land: 'Not the sea',
  lane: 'Narrow road',
  last: 'At the very end',
  late: 'After the time',
  lawn: 'Grass to mow',
  lead: 'Go first',
  leaf: 'It falls in autumn',
  leak: 'Water where it should not be',
  lean: 'Tip to one side',
  leap: 'A big jump',
  left: 'Not right',
  lend: 'Let them borrow it',
  life: 'Birth to death',
  lift: 'Pick it up',
  like: 'Be fond of',
  limb: 'Arm or leg',
  lime: 'Small green citrus',
  line: 'Straight mark',
  link: 'What joins the chain',
  lion: 'King of the beasts',
  list: 'One thing under another',
  load: 'What it carries',
  loaf: 'Whole bread',
  loan: 'Money lent',
  lock: 'It needs a key',
  loft: 'Room under the roof',
  lone: 'All by itself',
  long: 'Far from short',
  look: 'Turn your eyes to it',
  loop: 'Circle of rope',
  lord: 'Titled gentleman',
  lose: 'Not win',
  loud: 'Turn it down',
  love: 'The strongest liking',
  luck: 'Chance going your way',
  lump: 'A bump in it',
  lung: 'You breathe with two',
  mail: 'Letters and parcels',
  main: 'The most important',
  make: 'Build it',
  male: 'Not female',
  mall: 'Shops under one roof',
  mane: 'Hair on a lion',
  many: 'A great number',
  mark: 'A spot left behind',
  mask: 'It covers the face',
  mast: 'The sail hangs from it',
  mate: 'A good friend',
  maze: 'Easy to get lost in',
  meal: 'Breakfast, lunch or dinner',
  mean: 'Not generous',
  meat: 'What the butcher sells',
  meet: 'Come together',
  melt: 'Turn to liquid',
  mend: 'Fix what is broken',
  menu: 'What you can order',
  mild: 'Gentle, not strong',
  mile: 'Sixteen hundred metres',
  milk: 'It comes from a cow',
  mill: 'It grinds the grain',
  mind: 'What thinks',
  mine: 'Belonging to me',
  mint: 'Green herb, or where coins are made',
  miss: 'Not hit it',
  mist: 'Thin fog',
  mode: 'The way it is set',
  mood: 'How you feel today',
  moon: 'It goes round the earth',
  more: 'A larger amount',
  moss: 'Soft green on a stone',
  most: 'Nearly all of it',
  moth: 'It goes for the light',
  move: 'Shift it along',
  much: 'A lot',
  mule: 'Half horse, half donkey',
  nail: 'Hammer it in',
  name: 'What you are called',
  navy: 'Ships of a country',
  near: 'Not far',
  neat: 'Everything in its place',
  neck: 'Head sits on it',
  need: 'Cannot do without',
  nest: 'Where the eggs go',
  news: 'What happened today',
  next: 'The one after',
  nice: 'Pleasant enough',
  nine: 'One less than ten',
  node: 'Point where lines meet',
  none: 'Not one',
  noon: 'Twelve o\'clock',
  nose: 'You smell with it',
  note: 'A short message',
  numb: 'No feeling in it',
  oats: 'Porridge grain',
  obey: 'Do as told',
  once: 'One time only',
  only: 'Nothing else',
  onto: 'Up and on',
  open: 'Not shut',
  oval: 'Egg shaped',
  oven: 'It bakes',
  over: 'Finished, or above',
  pace: 'How fast you walk',
  pack: 'Put it in the case',
  page: 'One side of a sheet',
  pain: 'It hurts',
  pair: 'Two of them',
  pale: 'Very little colour',
  palm: 'Inside of the hand, or a beach tree',
  park: 'Grass and trees in town',
  part: 'Not the whole',
  pass: 'Go by it',
  past: 'Already gone',
  path: 'Narrow way on foot',
  peak: 'Top of the mountain',
  pear: 'Fruit shaped like a teardrop',
  peel: 'Take the skin off',
  pick: 'Choose it',
  pier: 'It walks out into the sea',
  pile: 'One on top of another',
  pink: 'Pale red',
  pipe: 'Water runs through it',
  plan: 'What you mean to do',
  play: 'What children do',
  plot: 'Patch of ground, or the story',
  plug: 'It goes in the socket',
  plum: 'Purple stone fruit',
  poem: 'Words with a rhythm',
  pole: 'Long straight stick',
  pond: 'Small still water',
  pool: 'Water to swim in',
  poor: 'Not much money',
  port: 'Where ships come in',
  pose: 'Hold still for the picture',
  post: 'Send it, or a wooden upright',
  pour: 'Tip it out',
  pray: 'Speak to a god',
  pull: 'Draw it towards you',
  pump: 'It moves the water',
  pure: 'Nothing else in it',
  push: 'Shove it away',
  quit: 'Give it up',
  race: 'First past the post',
  rail: 'Train runs on it',
  rain: 'Water from the sky',
  rank: 'Where you stand in order',
  rare: 'Hardly ever seen',
  rate: 'How fast, or what it costs',
  read: 'Take in the words',
  real: 'Not made up',
  rely: 'Count on it',
  rent: 'Money for a room',
  rest: 'Take a break',
  rice: 'It goes with curry',
  rich: 'Plenty of money',
  ride: 'Get on and go',
  ring: 'It goes on a finger',
  ripe: 'Ready to eat',
  rise: 'Go up',
  risk: 'A chance worth weighing',
  road: 'Cars go along it',
  roar: 'What a lion does',
  robe: 'Long loose gown',
  rock: 'Stone, or music with a beat',
  role: 'The part you play',
  roll: 'Turn over and over',
  roof: 'Top of the house',
  room: 'Four walls',
  root: 'It holds the plant down',
  rope: 'Thick cord',
  rose: 'Flower with thorns',
  rude: 'Bad mannered',
  ruin: 'Wreck it',
  rule: 'What you must follow',
  rush: 'Be in a hurry',
  sack: 'Big bag',
  safe: 'Out of danger',
  sail: 'It catches the wind',
  salt: 'It goes with pepper',
  same: 'No different',
  sand: 'The beach is made of it',
  save: 'Keep it for later',
  scan: 'Look it over quickly',
  seal: 'It claps on a rock',
  seat: 'Somewhere to sit',
  seed: 'A plant starts as one',
  seek: 'Go looking',
  self: 'Who you are',
  sell: 'Take the money for it',
  send: 'Post it off',
  ship: 'It crosses the sea',
  shoe: 'It goes on a foot',
  shop: 'Where you buy it',
  shot: 'One go with a gun or a camera',
  show: 'Let them see it',
  shut: 'Close it',
  sick: 'Not well',
  side: 'Left or right of it',
  sign: 'It tells you the way',
  silk: 'Smooth cloth from a worm',
  sing: 'Make a tune with your voice',
  sink: 'Go under, or where the dishes go',
  size: 'How big it is',
  skin: 'It covers you',
  slab: 'Thick flat piece',
  slam: 'Shut it hard',
  slim: 'Nicely thin',
  slip: 'Lose your footing',
  slow: 'Taking its time',
  snap: 'Break it clean',
  snow: 'White and cold',
  soap: 'It goes with water',
  sock: 'It goes inside the shoe',
  soft: 'Gentle to the touch',
  soil: 'What the garden grows in',
  sold: 'Gone to a buyer',
  sole: 'Bottom of a shoe',
  some: 'Not all',
  song: 'Words with a tune',
  soon: 'Before long',
  sort: 'Put it in order',
  soul: 'The inner part',
  soup: 'You eat it with a spoon',
  sour: 'Sharp like a lemon',
  span: 'Reach from side to side',
  spin: 'Turn on the spot',
  spot: 'A small round mark',
  star: 'It shines at night',
  stay: 'Do not go',
  stem: 'Stalk of a flower',
  step: 'One stair',
  stir: 'Give it a turn',
  stop: 'Go no further',
  stud: 'Small round fastener',
  such: 'Of that kind',
  suit: 'Jacket and trousers',
  swim: 'Move through water',
  tail: 'Behind the animal',
  take: 'Pick it up',
  tale: 'A story',
  talk: 'Use your voice',
  tall: 'Well above the rest',
  tame: 'Not wild',
  tank: 'It holds the water',
  tape: 'Sticky strip',
  task: 'A job to do',
  team: 'They play together',
  tear: 'Drop from the eye',
  tell: 'Let them know',
  tent: 'Canvas for the night',
  term: 'A word, or part of the school year',
  test: 'See if it works',
  text: 'The words on the page',
  than: 'More ___ enough',
  that: 'The other one',
  them: 'Those people',
  then: 'After that',
  thin: 'Not thick',
  this: 'The one here',
  tide: 'The sea coming and going',
  tidy: 'Everything put away',
  tile: 'It covers the roof',
  tilt: 'Lean it over',
  time: 'What the clock shows',
  tiny: 'Very small indeed',
  tire: 'Wear yourself out',
  toad: 'Warty hopper',
  tone: 'How a voice sounds',
  tool: 'It helps you do the job',
  torn: 'Ripped',
  tour: 'Trip round the sights',
  town: 'Bigger than a village',
  trap: 'It catches the mouse',
  tray: 'You carry the tea on it',
  tree: 'It has a trunk',
  trim: 'Cut it neat',
  trip: 'A journey, or a stumble',
  true: 'Not a word of a lie',
  tube: 'Hollow pipe',
  tune: 'A melody',
  turn: 'Change direction',
  twin: 'One of two born together',
  type: 'Kind, or use a keyboard',
  ugly: 'Hard on the eye',
  undo: 'Put it back as it was',
  unit: 'One of a set',
  upon: 'On top of',
  urge: 'A strong want',
  used: 'Not new',
  vase: 'Flowers stand in it',
  vast: 'Enormous',
  vein: 'Blood runs back through it',
  verb: 'A doing word',
  very: 'To a high degree',
  view: 'What you can see',
  visa: 'Stamp to enter a country',
  vote: 'Put your cross in the box',
  wade: 'Walk through water',
  wage: 'What the job pays',
  wait: 'Hang on a bit',
  wake: 'Stop sleeping',
  walk: 'Go on foot',
  wall: 'It holds the roof up',
  want: 'Wish you had it',
  ward: 'Room in a hospital',
  warm: 'Nicely hot',
  warn: 'Tell them before it happens',
  wash: 'Soap and water',
  wasp: 'It stings and it is not a bee',
  wave: 'The sea does it, and so does a hand',
  weak: 'Not strong',
  wear: 'Have it on',
  week: 'Seven days',
  well: 'In good health, or a hole for water',
  went: 'Set off',
  west: 'Where the sun goes down',
  what: 'Which thing',
  when: 'At what time',
  whom: 'Which person, formally',
  wide: 'A long way across',
  wife: 'Married woman',
  wild: 'Not tamed',
  will: 'Going to, or a last wish',
  wind: 'Moving air',
  wine: 'Grapes in a bottle',
  wing: 'A bird has two',
  wipe: 'Clean it with a cloth',
  wire: 'Thin metal thread',
  wise: 'Knows a thing or two',
  wish: 'What you want',
  wolf: 'It hunts in a pack',
  wood: 'Trees, or what they give',
  wool: 'It comes off a sheep',
  word: 'Letters that mean something',
  work: 'What you do for a wage',
  worm: 'It turns the soil',
  wrap: 'Put paper round it',
  yard: 'Three feet',
  yarn: 'Wool for knitting',
  yawn: 'What a tired mouth does',
  year: 'Twelve months',
  zeal: 'Keenness for the cause',
  zero: 'Nothing at all',
  zone: 'An area set apart',

  // Five letters
  about: 'Roughly, or on the subject of',
  above: 'Higher up',
  actor: 'They take the part',
  adopt: 'Take on as your own',
  adult: 'Grown up',
  after: 'Following on',
  agent: 'They act for you',
  agree: 'See it the same way',
  ahead: 'Out in front',
  alarm: 'It wakes you',
  album: 'Records, or where photos live',
  alert: 'Wide awake and watching',
  alien: 'From another world',
  alike: 'Much the same',
  alive: 'Not dead',
  alley: 'Narrow lane between buildings',
  allow: 'Let it happen',
  alone: 'Nobody else there',
  along: 'Beside it',
  aloud: 'Out where all can hear',
  alpha: 'First Greek letter',
  amber: 'Traffic light in the middle',
  among: 'In with the rest',
  angel: 'Winged helper',
  anger: 'Hot temper',
  angle: 'Two lines meeting',
  angry: 'Very cross',
  ankle: 'Joint above the foot',
  apart: 'Not together',
  apple: 'It keeps the doctor away',
  apply: 'Put in for the job',
  apron: 'It keeps the cook clean',
  arena: 'Where the crowd watches',
  argue: 'Row about it',
  arise: 'Get up, or come about',
  armed: 'Carrying a weapon',
  armor: 'Metal a knight wears',
  arrow: 'It flies from a bow',
  aside: 'Off to one side',
  asset: 'Something worth having',
  avoid: 'Keep well clear',
  awake: 'Not asleep',
  award: 'Prize for doing well',
  aware: 'Knows it is there',
  badge: 'Pin on the uniform',
  badly: 'Not at all well',
  baker: 'They make the bread',
  bacon: 'It goes with eggs',
  basic: 'Nothing fancy',
  basin: 'Bowl for washing',
  basis: 'What it rests on',
  batch: 'A lot baked at once',
  beach: 'Sand by the sea',
  beard: 'Hair on the chin',
  beast: 'Big wild animal',
  began: 'Made a start',
  begin: 'Make a start',
  being: 'A living thing',
  belly: 'Round the middle',
  below: 'Lower down',
  bench: 'Long seat',
  berry: 'Small soft fruit',
  birth: 'Coming into the world',
  black: 'Colour of coal',
  blade: 'Cutting edge',
  blame: 'Say whose fault it was',
  blank: 'Nothing written on it',
  blast: 'Big bang',
  blaze: 'A fire well going',
  bleak: 'Cold and cheerless',
  blend: 'Mix it smooth',
  bless: 'Wish good on',
  blind: 'Cannot see',
  block: 'Solid lump, or stop it',
  blood: 'It runs in your veins',
  bloom: 'Come into flower',
  blown: 'Carried off by the wind',
  blunt: 'Not sharp',
  blush: 'Go red in the face',
  board: 'Plank, or those who run it',
  boast: 'Blow your own trumpet',
  bonus: 'Extra on top',
  booth: 'Little box to stand in',
  boost: 'Give it a lift',
  bound: 'Tied, or a leap',
  brain: 'What does the thinking',
  brake: 'It stops the car',
  brand: 'Name on the label',
  brave: 'Not afraid',
  bread: 'Loaf on the table',
  break: 'Snap it, or a rest',
  breed: 'Raise the young',
  brick: 'Wall is built of them',
  bride: 'She is getting married',
  brief: 'Not long at all',
  bring: 'Fetch it here',
  brisk: 'Quick and lively',
  broad: 'Wide across',
  broke: 'Snapped, or with no money',
  brook: 'Little stream',
  broom: 'It sweeps the floor',
  brown: 'Colour of earth',
  brush: 'Paint or hair needs one',
  build: 'Put it up',
  built: 'Put up',
  bunch: 'A lot held together',
  burnt: 'Left too long on the heat',
  burst: 'Pop it open',
  cabin: 'Small wooden house',
  cable: 'Thick wire',
  camel: 'It crosses the desert',
  candy: 'Sweets',
  canal: 'Man-made waterway',
  canoe: 'You paddle it',
  carry: 'Take it with you',
  carve: 'Cut a shape',
  catch: 'Take it as it comes',
  cause: 'Why it happened',
  cease: 'Stop it altogether',
  chain: 'Links together',
  chair: 'You sit on it',
  chalk: 'It writes on the board',
  charm: 'What wins people over',
  chart: 'Table or a map',
  chase: 'Run after it',
  cheap: 'Costs very little',
  cheat: 'Break the rules',
  check: 'Make sure of it',
  cheek: 'Side of the face',
  cheer: 'Shout for the team',
  chess: 'Kings and pawns',
  chest: 'Box, or the front of you',
  chief: 'The one in charge',
  child: 'Young person',
  chill: 'A cold that gets in',
  choir: 'They sing together',
  chord: 'Notes played together',
  chose: 'Picked it',
  chunk: 'A thick lump',
  cider: 'Apples in a glass',
  civic: 'To do with the town',
  claim: 'Say it is yours',
  class: 'A group taught together',
  clean: 'Not a mark on it',
  clear: 'Nothing in the way',
  clerk: 'They keep the records',
  click: 'Small sharp sound',
  cliff: 'Steep drop to the sea',
  climb: 'Go up it',
  cloak: 'Loose coat with no sleeves',
  clock: 'It tells the time',
  close: 'Shut it, or near',
  cloth: 'Woven material',
  cloud: 'White in the sky',
  clown: 'They make the children laugh',
  coach: 'Bus, or the one who trains you',
  coast: 'Where land meets sea',
  cocoa: 'Hot chocolate drink',
  comet: 'It has a tail of ice',
  comic: 'Funny, or a picture paper',
  coral: 'The reef is made of it',
  couch: 'Sofa',
  cough: 'What a cold makes you do',
  could: 'Was able to',
  count: 'One, two, three',
  court: 'Where tennis or justice happens',
  cover: 'Put the lid on',
  crack: 'A thin split',
  craft: 'A skill with the hands',
  crane: 'Long-necked bird, or it lifts',
  crash: 'Hit it hard',
  crawl: 'Go on hands and knees',
  crazy: 'Out of your mind',
  cream: 'Top of the milk',
  creek: 'Small inlet',
  crest: 'Top of a hill or a wave',
  crime: 'Against the law',
  crisp: 'Snaps when you bend it',
  cross: 'Angry, or go over',
  crowd: 'A lot of people',
  crown: 'The king wears it',
  crude: 'Rough and unfinished',
  cruel: 'Hard on others',
  crush: 'Squash it flat',
  crust: 'Outside of the bread',
  curve: 'A bend with no corners',
  cycle: 'Round and round again',
  daily: 'Every single day',
  dairy: 'Milk and cheese come from it',
  dance: 'Move to the music',
  dated: 'Out of fashion',
  dealt: 'Handed out the cards',
  death: 'The end of life',
  debut: 'First time out',
  decay: 'Rot away',
  decor: 'How the room is done out',
  delay: 'Put it off',
  dense: 'Packed tight',
  depth: 'How deep it goes',
  derby: 'A local match',
  diary: 'Where the days are written',
  dirty: 'Needs a wash',
  ditch: 'Channel at the roadside',
  diver: 'They go under the water',
  dizzy: 'The room is spinning',
  dodge: 'Get out of its way',
  doing: 'Getting on with it',
  donor: 'They give',
  doubt: 'Not sure at all',
  dough: 'Bread before the oven',
  dozen: 'Twelve of them',
  draft: 'First try at writing',
  drain: 'Let the water out',
  drama: 'A play, or a fuss',
  drank: 'Put it away',
  drawn: 'Pulled, or sketched',
  dream: 'What you have asleep',
  dress: 'She puts one on',
  dried: 'No moisture left',
  drift: 'Float where it likes',
  drill: 'It makes a hole',
  drink: 'Take it down',
  drive: 'Take the wheel',
  drone: 'It buzzes, or it flies itself',
  drove: 'Took the car',
  drown: 'Go under and not come up',
  dryer: 'It takes the water out',
  dwell: 'Live there',
  eager: 'Cannot wait',
  eagle: 'Great bird of prey',
  early: 'Before the time',
  earth: 'The planet underfoot',
  easel: 'It holds the canvas',
  eight: 'One more than seven',
  elbow: 'Joint in the arm',
  elder: 'The older one',
  elect: 'Vote them in',
  elite: 'The chosen few',
  empty: 'Nothing in it',
  enemy: 'Not a friend',
  enjoy: 'Have a good time with it',
  enter: 'Come in',
  entry: 'The way in',
  equal: 'Just the same',
  error: 'A mistake',
  essay: 'A piece of writing',
  event: 'Something that happens',
  every: 'Each and all',
  exact: 'Right to the last bit',
  exist: 'Be there at all',
  extra: 'More than needed',
  fable: 'Story with a lesson',
  faint: 'Very weak, or pass out',
  fairy: 'Small winged being',
  faith: 'Belief without proof',
  false: 'Not true',
  fancy: 'Rather grand',
  fatal: 'It ends in death',
  fault: 'Whose mistake it was',
  favor: 'A good turn',
  feast: 'A very big meal',
  fence: 'It marks the boundary',
  ferry: 'Boat that goes back and forth',
  fever: 'Temperature up',
  fewer: 'Not so many',
  fiber: 'Thread, or what bread has',
  field: 'Open ground',
  fifth: 'After the fourth',
  fifty: 'Half a hundred',
  fight: 'Come to blows',
  final: 'The very last',
  first: 'Before all the rest',
  flame: 'Tongue of fire',
  flash: 'A sudden light',
  fleet: 'All the ships',
  flesh: 'What is under the skin',
  flick: 'A quick little movement',
  fling: 'Throw it hard',
  float: 'Sit on the water',
  flood: 'Too much water',
  floor: 'You stand on it',
  flour: 'It makes the bread',
  fluid: 'It runs and pours',
  flute: 'You blow across it',
  focus: 'Make it sharp',
  foggy: 'Hard to see through',
  force: 'Push or pull',
  forge: 'Where the smith works',
  forth: 'Out and onward',
  forty: 'Twice twenty',
  forum: 'Where it gets discussed',
  found: 'Came across it',
  frame: 'It goes round the picture',
  frank: 'Says it straight',
  fraud: 'A trick for money',
  fresh: 'Just picked',
  fried: 'Done in the pan',
  front: 'The face of it',
  frost: 'White on the grass',
  frown: 'Face of worry',
  fruit: 'Apples and the rest',
  fully: 'All the way',
  funny: 'It makes you laugh',
  giant: 'Very big indeed',
  given: 'Handed over',
  glass: 'You drink from it',
  globe: 'The world in the round',
  glory: 'Great honour',
  glove: 'It goes on a hand',
  going: 'On the way',
  grace: 'Easy beauty of movement',
  grade: 'What mark it gets',
  grain: 'Seed of the corn',
  grand: 'Very fine indeed',
  grant: 'Let them have it',
  grape: 'Wine starts as this',
  grasp: 'Take a firm hold',
  grass: 'You mow it',
  grave: 'Very serious',
  great: 'Really rather good',
  green: 'Colour of the grass',
  greet: 'Say hello',
  grief: 'Deep sadness',
  grill: 'Cook it under the heat',
  grind: 'Crush it to powder',
  gross: 'Whole, before anything is taken',
  group: 'A few together',
  grown: 'Got bigger',
  guard: 'They keep watch',
  guess: 'Have a stab at it',
  guest: 'They came to stay',
  guide: 'They show the way',
  guilt: 'What the wrongdoer feels',
  habit: 'What you always do',
  happy: 'Pleased with life',
  harsh: 'Rough and unkind',
  haste: 'Too much hurry',
  hatch: 'Small door, or come out of an egg',
  haunt: 'Where a ghost hangs about',
  heart: 'It beats',
  heavy: 'Hard to lift',
  hedge: 'Green fence',
  hello: 'First word on the phone',
  hence: 'For that reason',
  hobby: 'What you do for fun',
  holly: 'Berries at Christmas',
  honey: 'Bees make it',
  honor: 'Good name',
  horse: 'You ride it',
  hotel: 'You stay the night',
  hound: 'Hunting dog',
  house: 'Where the family lives',
  human: 'One of us',
  humid: 'Warm and sticky',
  humor: 'What makes it funny',
  hurry: 'Get a move on',
  image: 'A picture of it',
  imply: 'Say it without saying it',
  index: 'Where to find it in the book',
  inner: 'On the inside',
  input: 'What goes in',
  issue: 'A matter to settle',
  ivory: 'Cream white, from a tusk',
  jelly: 'It wobbles',
  jewel: 'Precious stone',
  joint: 'Where two bones meet',
  judge: 'They decide the case',
  juice: 'Squeezed from the fruit',
  knack: 'The trick of doing it',
  knife: 'It cuts',
  knock: 'Rap on the door',
  known: 'Everybody has heard of it',
  label: 'What it says on the tin',
  labor: 'Hard work',
  large: 'Well above average',
  laser: 'A very thin beam',
  later: 'After a while',
  laugh: 'What a joke gets',
  layer: 'One level of it',
  learn: 'Take it in',
  lease: 'Rent it for a term',
  least: 'The smallest amount',
  leave: 'Go away',
  legal: 'Allowed by law',
  lemon: 'Yellow and sharp',
  level: 'Flat and even',
  lever: 'Pull it to work the machine',
  light: 'It comes on at the switch',
  limit: 'As far as it goes',
  linen: 'Cloth from flax',
  liner: 'Big passenger ship',
  liver: 'It cleans the blood',
  lobby: 'Room inside the door',
  local: 'From round here',
  lodge: 'Small house in the grounds',
  logic: 'Sound reasoning',
  loose: 'Not tied down',
  lorry: 'Big goods vehicle',
  lower: 'Let it down',
  loyal: 'Sticks by you',
  lucky: 'Chance keeps going your way',
  lunar: 'To do with the moon',
  lunch: 'The midday meal',
  lying: 'Not telling the truth',
  magic: 'Tricks that look impossible',
  major: 'The bigger part',
  maker: 'They made it',
  maple: 'Its leaf is on a flag',
  march: 'Walk in step',
  marsh: 'Wet low ground',
  match: 'A game, or it lights the fire',
  maybe: 'It might be',
  mayor: 'Head of the town',
  meant: 'Intended it',
  medal: 'Hung round the winner',
  media: 'Papers and television',
  medic: 'Doctor in the field',
  melon: 'Big juicy summer fruit',
  mercy: 'Going easy on them',
  merge: 'Run together',
  merit: 'What it deserves',
  merry: 'In good spirits',
  metal: 'Iron, gold and the rest',
  meter: 'It measures',
  midst: 'Right in the middle',
  might: 'Strength, or it may happen',
  mimic: 'Copy them exactly',
  minor: 'The smaller part',
  minus: 'Take it away',
  mixed: 'Stirred together',
  model: 'A small copy, or they wear the clothes',
  moist: 'A little damp',
  money: 'Notes and coins',
  month: 'Thirty days or so',
  moral: 'What the story teaches',
  motel: 'Roadside stop for the night',
  motor: 'It turns the wheels',
  mount: 'Get up on it',
  mouse: 'It squeaks',
  mouth: 'Where the food goes in',
  movie: 'A film',
  music: 'What the band plays',
  naive: 'Too trusting',
  naked: 'Nothing on',
  nasty: 'Really unpleasant',
  naval: 'To do with ships of war',
  nerve: 'It carries the feeling',
  never: 'Not once',
  newly: 'Just lately',
  night: 'When it is dark',
  noble: 'High minded',
  noise: 'Unwanted sound',
  north: 'Top of the map',
  noted: 'Well known for it',
  novel: 'A long story',
  nurse: 'They look after the patient',
  nylon: 'Man-made thread',
  ocean: 'The great sea',
  offer: 'Put it forward',
  often: 'Many times',
  olive: 'Green and salty',
  onion: 'It makes you cry',
  onset: 'The very start',
  opera: 'Singing all the way through',
  orbit: 'Path round a planet',
  order: 'Ask for it, or put it straight',
  organ: 'Church instrument, or part of the body',
  other: 'Not this one',
  ought: 'Really should',
  ounce: 'Small weight',
  outer: 'On the outside',
  owner: 'It belongs to them',
  paint: 'It goes on the wall',
  panel: 'Flat board, or a group who decide',
  panic: 'Fright with no thinking',
  paper: 'You write on it',
  party: 'A good night in',
  pasta: 'Italian staple',
  paste: 'Thick and sticky',
  patch: 'A bit sewn over the hole',
  patio: 'Paved bit of the garden',
  pause: 'Stop for a moment',
  peace: 'No war at all',
  peach: 'Soft fuzzy fruit',
  pearl: 'It grows in an oyster',
  pedal: 'You push it with your foot',
  penny: 'Smallest coin',
  perch: 'Where a bird sits',
  phase: 'One stage of it',
  phone: 'You call on it',
  photo: 'Snap of the day',
  piano: 'Black and white keys',
  piece: 'One part of it',
  pilot: 'They fly the plane',
  pinch: 'Take it between finger and thumb',
  pitch: 'Where the match is played',
  pixel: 'One dot of the screen',
  pizza: 'Round with cheese on top',
  place: 'Where it is',
  plain: 'Nothing added',
  plane: 'It flies',
  plant: 'It grows in the ground',
  plate: 'Dinner goes on it',
  plaza: 'Open square in town',
  plumb: 'Straight up and down',
  point: 'Sharp end, or one score',
  polar: 'Of the far north or south',
  porch: 'Cover over the front door',
  pound: 'Weight, or money in Britain',
  power: 'What makes it go',
  press: 'Push down on it',
  price: 'What it costs',
  pride: 'Pleased with your own',
  prime: 'The very best of it',
  print: 'Put it on paper',
  prior: 'Before that',
  prize: 'What the winner takes',
  probe: 'Look into it',
  promo: 'A short advert',
  proof: 'It settles the argument',
  proud: 'Pleased with your own',
  prove: 'Show it is so',
  pulse: 'Beat of the blood',
  punch: 'Hit with the fist',
  pupil: 'One at school, or part of the eye',
  purse: 'She keeps her money in it',
  queen: 'She wears the crown',
  query: 'A question',
  quest: 'A long search',
  queue: 'Stand in line',
  quick: 'Fast off the mark',
  quiet: 'Hardly a sound',
  quilt: 'Warm cover for the bed',
  quite: 'Rather',
  quote: 'Say what they said',
  radar: 'It finds the plane',
  radio: 'You listen to it',
  raise: 'Lift it up',
  rally: 'Come together again',
  ranch: 'Big cattle farm',
  range: 'How far it reaches',
  rapid: 'Very fast',
  ratio: 'One compared with another',
  reach: 'Get to it',
  react: 'Answer what happened',
  ready: 'All set',
  realm: 'A kingdom',
  rebel: 'They will not go along with it',
  refer: 'Send them on to it',
  reign: 'Time on the throne',
  relax: 'Take it easy',
  relay: 'Pass it on, or a team race',
  renew: 'Make it good again',
  reply: 'Answer them',
  rider: 'They are on the horse',
  ridge: 'Long narrow top',
  rifle: 'Long gun',
  right: 'Not left, or not wrong',
  rigid: 'It will not bend',
  rinse: 'Wash the soap off',
  risky: 'It might go wrong',
  rival: 'The other side',
  river: 'It runs to the sea',
  roast: 'Cook it in the oven',
  robot: 'A machine that does the work',
  rocky: 'Full of stones',
  rough: 'Not smooth',
  round: 'Like a circle',
  route: 'The way to go',
  royal: 'Of the king or queen',
  rugby: 'Game with an oval ball',
  ruler: 'It measures, or they rule',
  rumor: 'What is going round',
  rural: 'Out in the country',
  salad: 'Green and cold',
  salon: 'Where the hair is done',
  sandy: 'Full of sand',
  satin: 'Smooth shiny cloth',
  sauce: 'It goes over the dish',
  scale: 'It weighs, or how big',
  scarf: 'It goes round the neck',
  scene: 'One part of the play',
  scent: 'A smell worth having',
  scope: 'How far it goes',
  score: 'How many you got',
  scout: 'They go ahead and look',
  scrap: 'A small leftover piece',
  sense: 'Sight, sound and the rest',
  serve: 'Bring it to the table',
  seven: 'One more than six',
  shade: 'Out of the sun',
  shaft: 'Long straight pole',
  shake: 'Move it to and fro',
  shall: 'Going to, formally',
  shame: 'What the wrongdoer feels',
  shape: 'Round, square or otherwise',
  share: 'Give each a part',
  shark: 'It has a fin',
  sharp: 'It cuts well',
  sheep: 'Wool on legs',
  sheet: 'It goes on the bed',
  shelf: 'Books stand on it',
  shell: 'The egg is in one',
  shift: 'Move it along',
  shine: 'Give off light',
  shirt: 'It has a collar',
  shock: 'A nasty surprise',
  shoot: 'Fire it, or a new green stem',
  shore: 'Edge of the sea',
  short: 'Not long',
  shout: 'Raise your voice',
  shown: 'Put on display',
  sight: 'What you can see',
  silly: 'Not at all sensible',
  since: 'From then on',
  sixth: 'After the fifth',
  sixty: 'Minutes in an hour',
  skill: 'What practice gives you',
  skirt: 'She wears one',
  slate: 'Grey roofing stone',
  sleep: 'Eight hours of it',
  slice: 'Cut a piece off',
  slide: 'Go smoothly along',
  slope: 'Ground on a tilt',
  small: 'Not big',
  smart: 'Sharp, or well turned out',
  smell: 'Take it in with your nose',
  smile: 'Turn the mouth up',
  smoke: 'It rises from the fire',
  snack: 'A small bite',
  snake: 'It slithers',
  sneak: 'Go quietly',
  solar: 'Of the sun',
  solid: 'Not liquid or gas',
  solve: 'Work it out',
  sorry: 'What you say when wrong',
  sound: 'What the ear picks up',
  south: 'Bottom of the map',
  space: 'Room, or out beyond the sky',
  spare: 'One kept in reserve',
  spark: 'Little jump of fire',
  speak: 'Use your voice',
  speed: 'How fast it goes',
  spell: 'Put the letters in order',
  spend: 'Part with the money',
  spice: 'It gives the dish a kick',
  spike: 'Sharp point',
  spine: 'Backbone',
  spite: 'Meanness for its own sake',
  split: 'Break it in two',
  spoke: 'Talked, or part of a wheel',
  spoon: 'It stirs the tea',
  sport: 'A game with rules',
  spray: 'Fine mist',
  squad: 'A small team',
  stack: 'Pile it up',
  staff: 'Those who work there',
  stage: 'Where the play happens',
  stain: 'A mark that will not come out',
  stair: 'One step of the flight',
  stake: 'Post in the ground, or what is risked',
  stall: 'Where they sell at the market',
  stamp: 'It goes on the letter',
  stand: 'Get to your feet',
  stare: 'Look and keep looking',
  start: 'Get going',
  state: 'How it is, or a country',
  steam: 'Boiling water in the air',
  steel: 'Hard strong metal',
  steep: 'A hard climb',
  steer: 'Point it where you want',
  stern: 'Strict, or the back of a ship',
  stick: 'Piece of wood, or it will not come off',
  stiff: 'It will not bend',
  still: 'Not moving, or even now',
  sting: 'What the bee does',
  stock: 'What is on the shelves',
  stone: 'A rock in the hand',
  stood: 'Was on its feet',
  stool: 'Seat with no back',
  store: 'Shop, or keep it',
  storm: 'Wind and rain together',
  story: 'A tale worth telling',
  stove: 'You cook on it',
  strap: 'Band that holds it on',
  straw: 'You drink through it',
  strip: 'Long narrow piece',
  study: 'Learn it properly',
  stuff: 'Things in general',
  style: 'How it is done',
  sugar: 'It sweetens the tea',
  suite: 'Rooms together',
  sunny: 'Not a cloud',
  super: 'Really rather good',
  sweet: 'Like sugar',
  swept: 'Cleaned with a broom',
  swift: 'Very quick',
  swing: 'It hangs in the park',
  sword: 'Long blade',
  table: 'It has four legs',
  taken: 'Somebody has it',
  taste: 'What the tongue tells you',
  teach: 'Show them how',
  teeth: 'You chew with them',
  tempo: 'Speed of the music',
  tenth: 'After the ninth',
  thank: 'Say you are grateful',
  theft: 'Taking what is not yours',
  their: 'Belonging to them',
  theme: 'What it is all about',
  there: 'In that place',
  these: 'The ones here',
  thick: 'Not thin',
  thief: 'They take what is not theirs',
  thigh: 'Top of the leg',
  thing: 'Any object at all',
  think: 'Use your head',
  third: 'After the second',
  those: 'The ones over there',
  three: 'One more than two',
  threw: 'Sent it through the air',
  throw: 'Send it through the air',
  thumb: 'The short fat finger',
  tiger: 'Orange with stripes',
  tight: 'No room to move',
  timer: 'It counts the minutes',
  tired: 'Ready for bed',
  title: 'Name of the book',
  toast: 'Bread under the grill',
  today: 'This very day',
  token: 'A small sign of it',
  tooth: 'One of thirty-two',
  topic: 'What it is about',
  torch: 'It shines in the dark',
  total: 'The whole lot added up',
  touch: 'Put a hand on it',
  tough: 'Hard going',
  towel: 'It dries you',
  tower: 'Tall and narrow',
  toxic: 'It poisons',
  trace: 'A faint sign left',
  track: 'Path, or what the train runs on',
  trade: 'Buying and selling',
  trail: 'Path through the country',
  train: 'It runs on rails',
  trait: 'Part of the character',
  treat: 'Something nice',
  trend: 'The way it is going',
  trial: 'A test, or a case in court',
  tribe: 'A people together',
  trick: 'A clever bit of business',
  tried: 'Gave it a go',
  tripe: 'Nonsense',
  troop: 'A band of soldiers',
  truck: 'Big goods vehicle',
  truly: 'Honestly',
  trunk: 'Tree stem, or an elephant\'s nose',
  trust: 'Believe in them',
  truth: 'What is really so',
  tulip: 'Spring flower in a cup shape',
  tumor: 'A lump that should not be there',
  tutor: 'They teach one to one',
  twice: 'Two times',
  twist: 'Turn it round',
  uncle: 'Your parent\'s brother',
  under: 'Below it',
  union: 'Joined together',
  unity: 'All as one',
  until: 'Up to that time',
  upper: 'Higher of the two',
  upset: 'Knocked over, or unhappy',
  urban: 'Of the town',
  urged: 'Pushed them to do it',
  usage: 'How it is used',
  usual: 'The way it always is',
  utter: 'Complete, or say it',
  vague: 'Not at all clear',
  valid: 'It holds good',
  value: 'What it is worth',
  valve: 'It lets the flow through',
  vapor: 'Liquid gone to the air',
  vault: 'Strong room, or leap over',
  venue: 'Where it is held',
  verse: 'Lines of a poem',
  video: 'Moving pictures',
  vigil: 'Keeping watch through the night',
  villa: 'House with a garden',
  vinyl: 'Records are made of it',
  viral: 'It spreads fast',
  virus: 'It makes you ill',
  visit: 'Go and see them',
  vital: 'Cannot do without it',
  vivid: 'Bright and clear',
  vocal: 'Done with the voice',
  voice: 'What you speak with',
  voter: 'They put the cross in the box',
  wagon: 'Cart pulled along',
  waist: 'Round the middle',
  waste: 'Throw it away for nothing',
  watch: 'It tells the time on your wrist',
  water: 'Two hydrogen and one oxygen',
  weary: 'Worn out',
  weave: 'Make cloth on a loom',
  wedge: 'Thick at one end',
  weigh: 'See how heavy',
  weird: 'Very strange',
  whale: 'Biggest in the sea',
  wheat: 'Bread starts as this',
  wheel: 'It goes round',
  where: 'In what place',
  which: 'What one',
  while: 'During that time',
  white: 'Colour of snow',
  whole: 'All of it',
  whose: 'Belonging to whom',
  widen: 'Make it broader',
  widow: 'Her husband has died',
  width: 'How wide',
  witch: 'Pointed hat and a broom',
  woman: 'Grown lass',
  world: 'Everywhere there is',
  worry: 'It sits on your mind',
  worse: 'Not as good',
  worth: 'What it is valued at',
  would: 'Was going to',
  wound: 'A cut that needs dressing',
  wrist: 'Between hand and arm',
  write: 'Put it on paper',
  wrong: 'Not right',
  yacht: 'Sailing boat for pleasure',
  yield: 'Give it up, or what the field gives',
  young: 'Not old',
  youth: 'Early years',
};
